### ISSUE TITLE
CHROMEBOOK: I updated Ubuntu 12.04 to Ubuntu 14.04 and now I can no longer start Ubuntu . What do you mean?

### ISSUE THREAD

**Issue by fabelix** [cerebrobr/topicos#11]
When typing ''sudo startunity'' displays the following information .

chronos@localhost / $ sudo startunity
Entering /mnt/stateful_partition/crouton/chroots/precise...

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.13.0
Release Date: 2012-09-05
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-54-highbank armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Thu Nov 5 11:24:12 PST 2015 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=73c2a408-d56b-f94f-b35e-a7c1fcc577bb/PARTNROFF=1 hashtree=PARTUUID=73c2a408-d56b-f94f-b35e-a7c1fcc577bb/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=aca0bfc065f33fe20dce89159778ccd1f3b544f1 salt=4ed576ffac585b70fb47e99216baaeb078e1a398dc5813419f299a32f4a5fdc8" noinitrd vt.global_cursor_default=0 kern_guid=73c2a408-d56b-f94f-b35e-a7c1fcc577bb  
Build Date: 05 November 2013  03:23:26PM
xorg-server 2:1.13.0-0ubuntu6.5~precise1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Nov 13 17:27:42 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
setversion 1.4 failed
crouton: version 1-20151104200003~master:2a1fc9da
release: precise
architecture: armhf
xmethod: xorg
targets: unity
host: version 7390.68.0 (Official Build) stable-channel daisy 
kernel: Linux localhost 3.8.11 #1 SMP Thu Nov 5 11:24:12 PST 2015 armv7l armv7l armv7l GNU/Linux
freon: yes
No Chromium OS X server is available.
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
Server terminated successfully (0). Closing log file.

Unmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost / $

**Comment by fdaciuk** [comment]
@fabelix:

> Neste repositório, você encontra uma série de documentos com informações de diversas tecnologias/ferramentas relacionadas em tópicos para estudos ou consultas rápidas.

https://github.com/cerebrobr/topicos/blob/master/README.md
